//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="ServiceReference.TextCasingSoapType")]
    public interface TextCasingSoapType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.TitleCaseWordsWithTokenResponse> TitleCaseWordsWithTokenAsync(ServiceReference.TitleCaseWordsWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.InvertStringCaseResponse> InvertStringCaseAsync(ServiceReference.InvertStringCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.InvertCaseFirstAdjustStringToPreviousResponse> InvertCaseFirstAdjustStringToPreviousAsync(ServiceReference.InvertCaseFirstAdjustStringToPreviousRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.InvertCaseFirstAdjustStringToCurrentResponse> InvertCaseFirstAdjustStringToCurrentAsync(ServiceReference.InvertCaseFirstAdjustStringToCurrentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.AllUppercaseWithTokenResponse> AllUppercaseWithTokenAsync(ServiceReference.AllUppercaseWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.AllLowercaseWithTokenResponse> AllLowercaseWithTokenAsync(ServiceReference.AllLowercaseWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.UppercaseWordsWithTokenResponse> UppercaseWordsWithTokenAsync(ServiceReference.UppercaseWordsWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.LowercaseWordsWithTokenResponse> LowercaseWordsWithTokenAsync(ServiceReference.LowercaseWordsWithTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleCaseWordsWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TitleCaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.TitleCaseWordsWithTokenRequestBody Body;
        
        public TitleCaseWordsWithTokenRequest()
        {
        }
        
        public TitleCaseWordsWithTokenRequest(ServiceReference.TitleCaseWordsWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class TitleCaseWordsWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public TitleCaseWordsWithTokenRequestBody()
        {
        }
        
        public TitleCaseWordsWithTokenRequestBody(string sText, string sToken)
        {
            this.sText = sText;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleCaseWordsWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TitleCaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.TitleCaseWordsWithTokenResponseBody Body;
        
        public TitleCaseWordsWithTokenResponse()
        {
        }
        
        public TitleCaseWordsWithTokenResponse(ServiceReference.TitleCaseWordsWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class TitleCaseWordsWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TitleCaseWordsWithTokenResult;
        
        public TitleCaseWordsWithTokenResponseBody()
        {
        }
        
        public TitleCaseWordsWithTokenResponseBody(string TitleCaseWordsWithTokenResult)
        {
            this.TitleCaseWordsWithTokenResult = TitleCaseWordsWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertStringCaseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertStringCase", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.InvertStringCaseRequestBody Body;
        
        public InvertStringCaseRequest()
        {
        }
        
        public InvertStringCaseRequest(ServiceReference.InvertStringCaseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertStringCaseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertStringCaseRequestBody()
        {
        }
        
        public InvertStringCaseRequestBody(string sAString)
        {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertStringCaseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertStringCaseResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.InvertStringCaseResponseBody Body;
        
        public InvertStringCaseResponse()
        {
        }
        
        public InvertStringCaseResponse(ServiceReference.InvertStringCaseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertStringCaseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertStringCaseResult;
        
        public InvertStringCaseResponseBody()
        {
        }
        
        public InvertStringCaseResponseBody(string InvertStringCaseResult)
        {
            this.InvertStringCaseResult = InvertStringCaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToPreviousRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToPrevious", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.InvertCaseFirstAdjustStringToPreviousRequestBody Body;
        
        public InvertCaseFirstAdjustStringToPreviousRequest()
        {
        }
        
        public InvertCaseFirstAdjustStringToPreviousRequest(ServiceReference.InvertCaseFirstAdjustStringToPreviousRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToPreviousRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertCaseFirstAdjustStringToPreviousRequestBody()
        {
        }
        
        public InvertCaseFirstAdjustStringToPreviousRequestBody(string sAString)
        {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToPreviousResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToPreviousResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.InvertCaseFirstAdjustStringToPreviousResponseBody Body;
        
        public InvertCaseFirstAdjustStringToPreviousResponse()
        {
        }
        
        public InvertCaseFirstAdjustStringToPreviousResponse(ServiceReference.InvertCaseFirstAdjustStringToPreviousResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToPreviousResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertCaseFirstAdjustStringToPreviousResult;
        
        public InvertCaseFirstAdjustStringToPreviousResponseBody()
        {
        }
        
        public InvertCaseFirstAdjustStringToPreviousResponseBody(string InvertCaseFirstAdjustStringToPreviousResult)
        {
            this.InvertCaseFirstAdjustStringToPreviousResult = InvertCaseFirstAdjustStringToPreviousResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToCurrentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToCurrent", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.InvertCaseFirstAdjustStringToCurrentRequestBody Body;
        
        public InvertCaseFirstAdjustStringToCurrentRequest()
        {
        }
        
        public InvertCaseFirstAdjustStringToCurrentRequest(ServiceReference.InvertCaseFirstAdjustStringToCurrentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToCurrentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertCaseFirstAdjustStringToCurrentRequestBody()
        {
        }
        
        public InvertCaseFirstAdjustStringToCurrentRequestBody(string sAString)
        {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToCurrentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToCurrentResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.InvertCaseFirstAdjustStringToCurrentResponseBody Body;
        
        public InvertCaseFirstAdjustStringToCurrentResponse()
        {
        }
        
        public InvertCaseFirstAdjustStringToCurrentResponse(ServiceReference.InvertCaseFirstAdjustStringToCurrentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToCurrentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertCaseFirstAdjustStringToCurrentResult;
        
        public InvertCaseFirstAdjustStringToCurrentResponseBody()
        {
        }
        
        public InvertCaseFirstAdjustStringToCurrentResponseBody(string InvertCaseFirstAdjustStringToCurrentResult)
        {
            this.InvertCaseFirstAdjustStringToCurrentResult = InvertCaseFirstAdjustStringToCurrentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllUppercaseWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllUppercaseWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.AllUppercaseWithTokenRequestBody Body;
        
        public AllUppercaseWithTokenRequest()
        {
        }
        
        public AllUppercaseWithTokenRequest(ServiceReference.AllUppercaseWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllUppercaseWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public AllUppercaseWithTokenRequestBody()
        {
        }
        
        public AllUppercaseWithTokenRequestBody(string sAString, string sToken)
        {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllUppercaseWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllUppercaseWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.AllUppercaseWithTokenResponseBody Body;
        
        public AllUppercaseWithTokenResponse()
        {
        }
        
        public AllUppercaseWithTokenResponse(ServiceReference.AllUppercaseWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllUppercaseWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AllUppercaseWithTokenResult;
        
        public AllUppercaseWithTokenResponseBody()
        {
        }
        
        public AllUppercaseWithTokenResponseBody(string AllUppercaseWithTokenResult)
        {
            this.AllUppercaseWithTokenResult = AllUppercaseWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllLowercaseWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllLowercaseWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.AllLowercaseWithTokenRequestBody Body;
        
        public AllLowercaseWithTokenRequest()
        {
        }
        
        public AllLowercaseWithTokenRequest(ServiceReference.AllLowercaseWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllLowercaseWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public AllLowercaseWithTokenRequestBody()
        {
        }
        
        public AllLowercaseWithTokenRequestBody(string sAString, string sToken)
        {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllLowercaseWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllLowercaseWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.AllLowercaseWithTokenResponseBody Body;
        
        public AllLowercaseWithTokenResponse()
        {
        }
        
        public AllLowercaseWithTokenResponse(ServiceReference.AllLowercaseWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllLowercaseWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AllLowercaseWithTokenResult;
        
        public AllLowercaseWithTokenResponseBody()
        {
        }
        
        public AllLowercaseWithTokenResponseBody(string AllLowercaseWithTokenResult)
        {
            this.AllLowercaseWithTokenResult = AllLowercaseWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UppercaseWordsWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UppercaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.UppercaseWordsWithTokenRequestBody Body;
        
        public UppercaseWordsWithTokenRequest()
        {
        }
        
        public UppercaseWordsWithTokenRequest(ServiceReference.UppercaseWordsWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class UppercaseWordsWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public UppercaseWordsWithTokenRequestBody()
        {
        }
        
        public UppercaseWordsWithTokenRequestBody(string sAString, string sToken)
        {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UppercaseWordsWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UppercaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.UppercaseWordsWithTokenResponseBody Body;
        
        public UppercaseWordsWithTokenResponse()
        {
        }
        
        public UppercaseWordsWithTokenResponse(ServiceReference.UppercaseWordsWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class UppercaseWordsWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UppercaseWordsWithTokenResult;
        
        public UppercaseWordsWithTokenResponseBody()
        {
        }
        
        public UppercaseWordsWithTokenResponseBody(string UppercaseWordsWithTokenResult)
        {
            this.UppercaseWordsWithTokenResult = UppercaseWordsWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LowercaseWordsWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LowercaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.LowercaseWordsWithTokenRequestBody Body;
        
        public LowercaseWordsWithTokenRequest()
        {
        }
        
        public LowercaseWordsWithTokenRequest(ServiceReference.LowercaseWordsWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class LowercaseWordsWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public LowercaseWordsWithTokenRequestBody()
        {
        }
        
        public LowercaseWordsWithTokenRequestBody(string sAString, string sToken)
        {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LowercaseWordsWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LowercaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference.LowercaseWordsWithTokenResponseBody Body;
        
        public LowercaseWordsWithTokenResponse()
        {
        }
        
        public LowercaseWordsWithTokenResponse(ServiceReference.LowercaseWordsWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class LowercaseWordsWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LowercaseWordsWithTokenResult;
        
        public LowercaseWordsWithTokenResponseBody()
        {
        }
        
        public LowercaseWordsWithTokenResponseBody(string LowercaseWordsWithTokenResult)
        {
            this.LowercaseWordsWithTokenResult = LowercaseWordsWithTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface TextCasingSoapTypeChannel : ServiceReference.TextCasingSoapType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class TextCasingSoapTypeClient : System.ServiceModel.ClientBase<ServiceReference.TextCasingSoapType>, ServiceReference.TextCasingSoapType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TextCasingSoapTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(TextCasingSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), TextCasingSoapTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TextCasingSoapTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TextCasingSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TextCasingSoapTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TextCasingSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TextCasingSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.TitleCaseWordsWithTokenResponse> ServiceReference.TextCasingSoapType.TitleCaseWordsWithTokenAsync(ServiceReference.TitleCaseWordsWithTokenRequest request)
        {
            return base.Channel.TitleCaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.TitleCaseWordsWithTokenResponse> TitleCaseWordsWithTokenAsync(string sText, string sToken)
        {
            ServiceReference.TitleCaseWordsWithTokenRequest inValue = new ServiceReference.TitleCaseWordsWithTokenRequest();
            inValue.Body = new ServiceReference.TitleCaseWordsWithTokenRequestBody();
            inValue.Body.sText = sText;
            inValue.Body.sToken = sToken;
            return ((ServiceReference.TextCasingSoapType)(this)).TitleCaseWordsWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.InvertStringCaseResponse> ServiceReference.TextCasingSoapType.InvertStringCaseAsync(ServiceReference.InvertStringCaseRequest request)
        {
            return base.Channel.InvertStringCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.InvertStringCaseResponse> InvertStringCaseAsync(string sAString)
        {
            ServiceReference.InvertStringCaseRequest inValue = new ServiceReference.InvertStringCaseRequest();
            inValue.Body = new ServiceReference.InvertStringCaseRequestBody();
            inValue.Body.sAString = sAString;
            return ((ServiceReference.TextCasingSoapType)(this)).InvertStringCaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.InvertCaseFirstAdjustStringToPreviousResponse> ServiceReference.TextCasingSoapType.InvertCaseFirstAdjustStringToPreviousAsync(ServiceReference.InvertCaseFirstAdjustStringToPreviousRequest request)
        {
            return base.Channel.InvertCaseFirstAdjustStringToPreviousAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.InvertCaseFirstAdjustStringToPreviousResponse> InvertCaseFirstAdjustStringToPreviousAsync(string sAString)
        {
            ServiceReference.InvertCaseFirstAdjustStringToPreviousRequest inValue = new ServiceReference.InvertCaseFirstAdjustStringToPreviousRequest();
            inValue.Body = new ServiceReference.InvertCaseFirstAdjustStringToPreviousRequestBody();
            inValue.Body.sAString = sAString;
            return ((ServiceReference.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToPreviousAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.InvertCaseFirstAdjustStringToCurrentResponse> ServiceReference.TextCasingSoapType.InvertCaseFirstAdjustStringToCurrentAsync(ServiceReference.InvertCaseFirstAdjustStringToCurrentRequest request)
        {
            return base.Channel.InvertCaseFirstAdjustStringToCurrentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.InvertCaseFirstAdjustStringToCurrentResponse> InvertCaseFirstAdjustStringToCurrentAsync(string sAString)
        {
            ServiceReference.InvertCaseFirstAdjustStringToCurrentRequest inValue = new ServiceReference.InvertCaseFirstAdjustStringToCurrentRequest();
            inValue.Body = new ServiceReference.InvertCaseFirstAdjustStringToCurrentRequestBody();
            inValue.Body.sAString = sAString;
            return ((ServiceReference.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToCurrentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AllUppercaseWithTokenResponse> ServiceReference.TextCasingSoapType.AllUppercaseWithTokenAsync(ServiceReference.AllUppercaseWithTokenRequest request)
        {
            return base.Channel.AllUppercaseWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AllUppercaseWithTokenResponse> AllUppercaseWithTokenAsync(string sAString, string sToken)
        {
            ServiceReference.AllUppercaseWithTokenRequest inValue = new ServiceReference.AllUppercaseWithTokenRequest();
            inValue.Body = new ServiceReference.AllUppercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ServiceReference.TextCasingSoapType)(this)).AllUppercaseWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AllLowercaseWithTokenResponse> ServiceReference.TextCasingSoapType.AllLowercaseWithTokenAsync(ServiceReference.AllLowercaseWithTokenRequest request)
        {
            return base.Channel.AllLowercaseWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AllLowercaseWithTokenResponse> AllLowercaseWithTokenAsync(string sAString, string sToken)
        {
            ServiceReference.AllLowercaseWithTokenRequest inValue = new ServiceReference.AllLowercaseWithTokenRequest();
            inValue.Body = new ServiceReference.AllLowercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ServiceReference.TextCasingSoapType)(this)).AllLowercaseWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.UppercaseWordsWithTokenResponse> ServiceReference.TextCasingSoapType.UppercaseWordsWithTokenAsync(ServiceReference.UppercaseWordsWithTokenRequest request)
        {
            return base.Channel.UppercaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.UppercaseWordsWithTokenResponse> UppercaseWordsWithTokenAsync(string sAString, string sToken)
        {
            ServiceReference.UppercaseWordsWithTokenRequest inValue = new ServiceReference.UppercaseWordsWithTokenRequest();
            inValue.Body = new ServiceReference.UppercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ServiceReference.TextCasingSoapType)(this)).UppercaseWordsWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.LowercaseWordsWithTokenResponse> ServiceReference.TextCasingSoapType.LowercaseWordsWithTokenAsync(ServiceReference.LowercaseWordsWithTokenRequest request)
        {
            return base.Channel.LowercaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.LowercaseWordsWithTokenResponse> LowercaseWordsWithTokenAsync(string sAString, string sToken)
        {
            ServiceReference.LowercaseWordsWithTokenRequest inValue = new ServiceReference.LowercaseWordsWithTokenRequest();
            inValue.Body = new ServiceReference.LowercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ServiceReference.TextCasingSoapType)(this)).LowercaseWordsWithTokenAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TextCasingSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TextCasingSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TextCasingSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.dataaccess.com/webservicesserver/TextCasing.wso");
            }
            if ((endpointConfiguration == EndpointConfiguration.TextCasingSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.dataaccess.com/webservicesserver/TextCasing.wso");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TextCasingSoap,
            
            TextCasingSoap12,
        }
    }
}
